feat: added send email to verification user
RoutinelyOrganization/routinely-api pull request #83
Opened 2024-09-22 13:14 UTC by staviasz

# Mudanças

## Tipo de PR

Marque todos os necessários

- [ ] Bug fix 
- [ ] Documentation 
- [ ] Feature 
- [ ] Refactor 
- [ ] Tests E2E 
- [ ] Tests unit 

## 🎯 Objetivo

## Alterações

## Requisitos de aceite

## Testes

## Tarefas pós-implantação

## 🛃 Para controle

- [ ] Testei as mudanças
- [ ] Atendeu aos [requisitos de aceite](#requisitos-de-aceite)
- [ ] Está sincronizada com a _branch **develop**_
- [ ] Conflitos entre _branches_ resolvidos

2024-09-22 17:42 UTC, erickmarx requested changes

2024-09-22 17:42 UTC, erickmarx commented on package.json
> +    "crypto-js": "^4.2.0",
Você pode e deve utilizar o modulo crypto do NodeJS, este pacote foi descontinuado.

https://nodejs.org/api/crypto.html

2024-09-22 17:42 UTC, erickmarx commented on src/modules/Account/account.controller.ts
> +    { name, email, password, acceptedTerms }: CreateAccountControllerInput,
Ao invés de desestruturar e construir outro objeto ao passar para o método `this.accountService.createAccount`, bote em uma variável "body" ou "data", isso facilita a leitura.

2024-09-22 17:42 UTC, erickmarx commented on src/modules/Account/account.controller.ts
> +    const { message } = await this.accountService.createAccount(
Passe a variável `data` do @Body no primeiro parâmetro

2024-09-22 17:42 UTC, erickmarx commented on src/modules/Account/account.controller.ts
> +    try {
Este try catch é redundante, o ESLint do NestJS não alertou?

2024-09-22 17:42 UTC, erickmarx commented on src/modules/Account/account.controller.ts
> +    } catch (e) {
Todo método do NodeJS, em especial métodos assíncronos, é protegido por try-catch.

Se não for alterar o comportamento do catch, pode deixar ele implícito.

2024-09-22 17:42 UTC, erickmarx commented on src/modules/Account/account.service.ts
> +    const queryUrlTemplate = this.encrypt(
Adapte para o modulo Node Crypto

2024-09-22 17:42 UTC, erickmarx commented on src/modules/Account/account.service.ts
> +    const queryString = this.decrypt(Object.keys(query)[0]);
Adapte para o modulo Node Crypto

2024-09-23 17:42 UTC, staviasz commented on package.json
> +    "crypto-js": "^4.2.0",
ja esta sendo usado, so esqueci de apagar o crypto-js do package.json

2024-09-23 17:47 UTC, staviasz commented on src/modules/Account/account.controller.ts
> +    try {
nem o eslint, nem eu reparei fui na onda do codeium e deixei

2024-09-23 17:50 UTC, staviasz commented on src/modules/Account/account.controller.ts
> +    try {
observando, aqui vi que todos os metodos foram construidos dessa forma, então acho melhor manter o padrão na proxima api seremos mais cuidadosos com isso

2024-09-23 17:52 UTC, staviasz commented on src/modules/Account/account.service.ts
> +    const queryUrlTemplate = this.encrypt(
ja esta utilizando o crypto, esse é um metodo que cirei na classe para facilitar

2024-09-23 17:53 UTC, staviasz commented on src/modules/Account/account.service.ts
> +    const queryString = this.decrypt(Object.keys(query)[0]);
o decrypt ja esta utilizando o crypto, é um metodo da propria classe que faz a logica do crypto

2024-09-23 17:54 UTC, staviasz commented on src/modules/Account/account.controller.ts
> +    { name, email, password, acceptedTerms }: CreateAccountControllerInput,
corrigido

2024-09-23 17:54 UTC, staviasz commented on src/modules/Account/account.controller.ts
> +    const { message } = await this.accountService.createAccount(
corrigido

2024-09-23 17:54 UTC, staviasz commented on src/modules/Account/account.controller.ts
> +    } catch (e) {
realmente não entendi por que esta assim

2024-09-30 14:49 UTC, merged